Repository tomschr/dbcookbook, pull requests merged in 2018-05, with the labels that each got.

#31 Update issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/issue_template.md
Labels: enhancement :octocat:, tools :wrench:

#30 Fix #27, correct canonical DocBook XSL URI
  en/xml/common/enumerate/number.xsl
  en/xml/common/personname/personname.xsl
  en/xml/common/titles/titles.xsl
  en/xml/common/topic.dbxsl-customization.xml
  en/xml/common/xpath.location/docbook-pi.xsl
  en/xml/fo/design-titlepages/mybooktitlepage.xsl
  en/xml/fo/initials/db-initials.xsl
  en/xml/fo/initials/initials-float.xsl
  en/xml/fo/line-height/line-height.xsl
  en/xml/html/breadcrumbs/chunk4breadcrumbs.xsl
  en/xml/html/move-toc/db-move-toc.xsl
  en/xml/html/permalinks/db-permalinks.xsl
  en/xml/html/simplenavig/db-simple-navigation.xsl
  en/xml/html/syntaxhighlight/sh-google.xsl
  en/xml/structure/adding-indexterms/add-indexterms.xsl
  en/xml/structure/dublin-core/db2dc.xsl
  en/xml/structure/splitdb/dbsplit.xsl
Labels: bug :bug:

#32 Add comment to point to issue#12
  en/xml/colophon.xml
Labels: enhancement :octocat:

#35 removed dead link to old.nabble.com
  en/xml/fo/topic.line-height.xml
Labels: bug :bug:
